### ISSUE TITLE
python manage.py migrate [Failure]

### ISSUE THREAD

**Issue by BenjaminHCCarr** [OpenHumans/genevieve#7]
Running manage.py:

> (genevieve) tyr:~/Code/Virtualenvs/genevieve (master) benc$ python manage.py migrate
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/Users/benc/Code/Virtualenvs/genevieve/lib/python2.7/site-packages/django/core/management/**init**.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "/Users/benc/Code/Virtualenvs/genevieve/lib/python2.7/site-packages/django/core/management/**init**.py", line 327, in execute
>     django.setup()
>   File "/Users/benc/Code/Virtualenvs/genevieve/lib/python2.7/site-packages/django/**init**.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/Users/benc/Code/Virtualenvs/genevieve/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
>     app_config.import_models(all_models)
>   File "/Users/benc/Code/Virtualenvs/genevieve/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/**init**.py", line 37, in import_module
>     **import**(name)
>   File "/Users/benc/Code/Virtualenvs/genevieve/genevieve_client/models.py", line 238, in <module>
>     class OpenHumansUser(ConnectedUser):
>   File "/Users/benc/Code/Virtualenvs/genevieve/genevieve_client/models.py", line 251, in OpenHumansUser
>     '?client_id={}&response_type=code'.format(CLIENT_ID))
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
> (genevieve) tyr:~/Code/Virtualenvs/genevieve (master) benc$ 

Both servers are running:

> (genevieve) tyr:~/Code/Virtualenvs/genevieve (master) benc$ brew services list
> Name       Status  User Plist
> ddclient   started root /Library/LaunchDaemons/homebrew.mxcl.ddclient.plist
> mariadb    stopped  
> memcached  stopped  
> php55      stopped  
> postgresql started benc /Users/benc/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
> rabbitmq   started benc /Users/benc/Library/LaunchAgents/homebrew.mxcl.rabbitmq.plist
> redis      stopped      

I think README.md needs to include a brief postgresql, there is alot of empty lines in .env, perhaps an example that's not blank would be useful

**Comment by madprime** [comment]
I've updated the README, see if notes for creating a postgres database help?
